export * from './validade/validade.component';
export * from './oferta-popup/oferta-popup.component';
export * from './informacao-produto/informacao-produto.component';
export * from './produto-popup/produto-popup.component';
export * from './validade-popup/validade-popup.component';
export * from './inclusao-produto/inclusao-produto.component';
export * from './descricao-produto/descricao-produto.component';
export * from './atendimento-popup/atendimento-popup.component';
export * from './filtro-atendimento/filtro-atendimento.component';
export * from './titulos-popup/titulos-popup.component';
export * from './cadastro-oportunidade/cadastro-oportunidade.component'
export * from './dashboard-mail-item/dashboard-mail-item.component'
export * from './definir-meta-popup/definir-meta-popup.component'
export * from './historico-pedidos/historico-pedidos.component'
export * from './atendimento-sac/atendimento-sac.component'
export * from './mix-ideal-popup/mix-ideal-popup.component'
export * from './devolucoes-popup/devolucoes-popup.component'
export * from './item-historico-popup/item-historico-popup.component'
export * from './historico-cobranca/historico-cobranca.component'
export * from './config-tabela-popup/config-tabela-popup.component'
export * from './messages-mail-item/messages-mail-item.component'
export * from './message-popup/message-popup.component'
export * from './tipoentrega-popup/tipoentrega-popup.component'
export * from './filial-retira/filial-retira.component'
export * from './tipo-entrega/tipo-entrega.component'
